### ISSUE TITLE
num_hours seems to be not honored

### ISSUE THREAD

**Issue by umrath** [decompil3d/lovelace-hourly-weather#2]
The latest version currently available via HACS does not seem to honor "num_hours".
If I set it to num_hours: '8' I will still get the same view as if I leave at with the default (12).

**Comment by umrath** [comment]
```
type: custom:hourly-weather
entity: weather.openweathermap
num_hours: '8'
name: Stündliches Wetter
```

Actually, I have noticed that it does change something. Just not the way I expected:
When configuring 8 hours, I would expect to, well, see 8 hours.
In reality I see a lot more than that:

![image](https://user-images.githubusercontent.com/1010437/174625267-08011667-f13b-4013-a63b-24ef9d0a8c43.png)

**Comment by decompil3d** [comment]
Oh, I see the problem. Look at your hourly weather data source -- I bet it has forecast entries that are more than one hour spacing. The card is properly showing 8 forecast entries, but each entry seems to be representing 3 hours. You can check this by looking at the weather entity you're using in the developer tools and checking the `forecast` attribute.

**Comment by umrath** [comment]
Ok, then maybe this configuration option should be renamed to "sections to display" or the like.

I tried to tune it down to 3 (which would equal 9 hours) but run into the next issue:
![image](https://user-images.githubusercontent.com/1010437/174726971-0901b4c5-cd96-406a-891d-6811d61f7c58.png)

**Comment by decompil3d** [comment]
The validation warning is by design. Since the bar is designed for even numbers of increments. You'll notice that even though you specified 3, it will show more segments than that.

I'll consider adding a warning when folks choose an entity that has forecast segments more than 1 hour apart though. The OpenWeatherMap integration can give you one-hour granularity data if you choose the `onecall_hourly` option. You can have more than one instance of that integration too, so if you like having the existing one you have, you can just add a second instance with a slightly different location (off by a tiny fraction of a degree latitude or longitude) and choose `onecall_hourly` for that one.
