### ISSUE TITLE
Colors should be linked to the weather type (or customizable)

### ISSUE THREAD

**Issue by tigers75** [decompil3d/lovelace-hourly-weather#24]
**Is your feature request related to a problem? Please describe.**
Why "sunny" weather is "light blue?"

**Describe the solution you'd like**
It'd be best to have colors that match the state like orange for sunny, gray for cloud or fog, blue for rain, etc.

**Describe alternatives you've considered**
Cant' think of anything without changing the code.

**Comment by noxhirsch** [comment]
I agree - I first thought that light blue means light rain ;)

**Comment by decompil3d** [comment]
I was going for blue sky, but I agree that customizable colors would be good. I'll use this issue to track adding that capability. Will probably accept a set of css colors.

**Comment by Valdorama** [comment]
First off, this is a fabulous project. I've been wanting something to replicate the Dark Sky hourly weather graph for ages. I also think using blue for clear/sunny conditions is a bit confusing. I believe Dark Sky doesn't have separate colours for 'clear' and 'sunny' either. At the moment my LHW card looks like this:

![image](https://user-images.githubusercontent.com/34754485/176926297-4d12e0d5-fe47-49d0-8f68-aa5b2f91d35a.png)

Having the black for the clear condition looks a bit odd to me. Customizable colours would be great, or failing that I'd like 'clear' and 'sunny' to be the same (pale grey) colour, since during the day clear implies sunny.

**Comment by decompil3d** [comment]
I'm working (slowly) on customizable color support. I'm also curious what colors folks would want for defaults. I'm considering changing the partly cloudy gray to more of a washed out blue. Feel free to comment suggestions here.

**Comment by Valdorama** [comment]
My preference would be to mimic the Dark Sky colours i.e. very pale grey for clear, then increasing levels of grey for increasing cloud coverage ('partly cloudy', 'mostly cloudy' etc.). Pale blue for light rain and increasing levels of blue for increasing precipitation intensity.
