### ISSUE TITLE
Time Format

### ISSUE THREAD

**Issue by bbday** [decompil3d/lovelace-hourly-weather#368]
Is possible change time format instead 2 PM (12h) to 14:00 (24h) ?
Thanks

**Comment by decompil3d** [comment]
The card should match your Home Assistant profile settings. So go to your profile page in the sidebar and choose whatever locale and time settings you prefer.

If that's not helping, let me know what your profile settings are and what locale you've chosen for your HA install.

**Comment by bbday** [comment]
you have right, sorry.

**Comment by pstaubs** [comment]
I have stumbled here and I would like to request this issue be reopened, there is a pretty clear use case not covered by [decompil3d](https://github.com/decompil3d)'s answer. Namely:

Date formatting isn't strictly only a locale issue. Indicating the Day of Week (Monday, Tuesday, Wednesday, ...) is a fundamentally different approach and use case to reading dates, especially for normies reading a forecast, rather than formated date (i.e. March 13). Formatted dates are just not that user-friendly for reading a forcast.
