### ISSUE TITLE
Can't card-mod title

### ISSUE THREAD

**Issue by jracoma** [decompil3d/lovelace-hourly-weather#396]
Hello. I've been trying to apply card-mod to the title name but am struggling. I've this variations of below but without success. It should just be for the element before shadow-dom but I'm not sure.

```
ha-card$: |
  h1 {
    font-size: 12px;
  }
```

Thanks!

**Comment by decompil3d** [comment]
card-mod can be tricky. The card title is a child of the `ha-card` shadow root, which is effectively the first shadow root down. Your current code is diving into the shadow root _within_ `ha-card`, which gets you to the card content rather than the chrome around the card.

This should work better:

```yaml
$: |
  h1.card-header {
    font-size: 12px;
  }
```

The `$` tells card-mod to dive into the first shadow root. And the `h1.card-header` selector is because there is an existing style on `.card-header` so we must be slightly more specific to override the font-size in there.

**Comment by jracoma** [comment]
Thanks for quick response!
