### ISSUE TITLE
Add icons to hourly weather bar

### ISSUE THREAD

**Issue by mehhhhhhhhhhhhhhhhhhhhhhhhhh** [decompil3d/lovelace-hourly-weather#4]
**Is your feature request related to a problem? Please describe.**
Card works as intended, but often the weather conditions aren't displayed.  In this case it would be beneficial to have an icon displayed to give indication to what the color represents.

**Describe the solution you'd like**
An option to display icons on the hourly weather bar.

**Describe alternatives you've considered**
A smaller font to show weather conditions could help, but icons seem more elegant.

**Comment by decompil3d** [comment]
How do you feel about an icon mode? That is, a config option to show icons _instead of_ text labels. The text labels will only show when a segment is >= 120px wide, but I could make icons show when a segment is as small as around 40px.

The way the code is written, it's easier to have it be either text labels OR icons. Would be harder and more brittle to support text labels for wider space and icons for smaller space.

Also note that I may also implement #8 with tooltip, so that may also help here.

Unless folks feel strongly about having both text and icons, I'll stick with the either/or plan described above.

**Comment by mehhhhhhhhhhhhhhhhhhhhhhhhhh** [comment]
Icon mode would be great!

**Comment by mghinch** [comment]
FWIW, I'm having the same problem (weather changes too frequently around here). An icon mode would be great, and would also work well for smaller wall displays too.
