### ISSUE TITLE
A question about starting hour

### ISSUE THREAD

**Issue by giobuc** [decompil3d/lovelace-hourly-weather#580]
Hi, 
thank you for your work, i really like it!!  🙂 

I have a question, is there a way to start everyday at 07.00 and stop at 23.00 regardless the actual hour?

Thank you
Giobuc

**Comment by decompil3d** [comment]
Glad you like the card 🙂 

The answer is: sort of. You cannot show past forecasts, since the underlying entity won't provide that information. But if you are ok with showing whatever the _next_ 07.00-23.00 block is (e.g. today if it's before 07.00, or tomorrow if it's after 07.00), then you could do this with templates:

```py
# Use this template for the `offset` config field
{% set now_hour = now().hour %}
{% set offset = (7 - now_hour) | abs %}
{{ offset }}
```

Then `num_segments` would be `16`.

You could also consider showing 07.00 _or_ now, depending on whether it's before or after 07.00. If you want to do that, the template gets slightly more complex:

```py
# For `offset`:
{% set now_hour = now().hour %}
{% set offset = max((7 - now_hour), 0) %}
{{ offset }}

# For `num_segments`:
{% set now_hour = now().hour %}
{% set num_segments = 23 - max(now_hour, 7) %}
{{ num_segments }}
```

Hope this helps.
